const MOUNTAIN_LIBRARY=[
{id:'hermon',number:1,name:'החרמון',zone:'north',riddle:'אני ההר הגבוה מכולם במדינה, מכנים אותי "העיניים של המדינה" והפסגה שלי מתכסה בשלג לבן בכל חורף. מי אני?',hint:'בקצה הצפון, סמוך לגבול סוריה ולבנון.',position:{x:92.48,y:.89},displayPosition:{x:89.8,y:5.8},hitEllipse:{x:92.48,y:.89,rx:3.2,ry:1.6},location:'צפון רמת הגולן',type:'רכס ופסגה',height:'הפסגה הגבוהה בישראל',feature:'שלג בחורף ותצפית אסטרטגית.',importance:'יוצא דופן גאולוגי ביחס לשדרת ההר המרכזית.',featureChoices:['שלג בחורף ותצפית אסטרטגית','נמצא לחוף הים התיכון','הר געש פעיל'],featureAnswer:'שלג בחורף ותצפית אסטרטגית'},
{id:'meron',number:2,name:'הר מירון',zone:'north',riddle:'אני מהווה את הפסגה הגבוהה ביותר באזור הגליל, ובכל שנה עולים אליי אלפי אנשים לחגוג את הילולת הרשב״י. מי אני?',hint:'בגליל העליון, ליד מירון.',position:{x:71.11,y:8.87},hitEllipse:{x:71.11,y:8.87,rx:3.0,ry:1.45},location:'הגליל העליון',type:'פסגה',height:'הפסגה הגבוהה בגליל',feature:'אתר הילולת הרשב״י.',importance:'נקודת גובה מרכזית בשדרת ההר הצפונית.',featureChoices:['אתר הילולת הרשב״י','מכתש גדול','נמל ימי'],featureAnswer:'אתר הילולת הרשב״י'},
{id:'tabor',number:3,name:'הר תבור',zone:'north',riddle:'יש לי צורה עגולה, כיפתית וייחודית מאוד, ואני בולט בבטחה מעל עמק יזרעאל הפתוח. מי אני?',hint:'במזרח הגליל התחתון.',position:{x:70.11,y:17.13},hitEllipse:{x:70.11,y:17.13,rx:3.0,ry:1.5},location:'הגליל התחתון',type:'הר בודד',height:'הר כיפתי בולט',feature:'צורה עגולה ובולטת מעל עמק יזרעאל.',importance:'נקודת ציון נופית והיסטורית.',featureChoices:['צורה עגולה ובולטת מעל עמק יזרעאל','רכס ארוך לאורך החוף','דיונות חול'],featureAnswer:'צורה עגולה ובולטת מעל עמק יזרעאל'},
{id:'gilboa',number:4,name:'הגלבוע',zone:'north',riddle:'על מדרונותיי התרחש הקרב שבו נפלו שאול המלך ובניו, ובכל אביב אני מתמלא בפריחה סגולה ומפורסמת של פרחי האירוס. מי אני?',hint:'מעל עמק המעיינות ובית שאן.',position:{x:70.54,y:22.18},hitEllipse:{x:70.54,y:22.18,rx:5.2,ry:3.2},location:'מעל עמק חרוד ובית שאן',type:'רכס הרים',height:'רכס אזורי',feature:'קרב שאול ופריחת אירוס הגלבוע.',importance:'רכס המשקיף על עמק המעיינות.',featureChoices:['קרב שאול ופריחת אירוס הגלבוע','שלג כל השנה','מכתש סחיפה'],featureAnswer:'קרב שאול ופריחת אירוס הגלבוע'},
{id:'carmel',number:5,name:'הכרמל',zone:'north',riddle:'מכנים אותי "ההר הירוק כל ימות השנה" בזכות החורש הטבעי שלי, ואני מגיע עד לעיר חיפה ונושק שם ישירות לים. מי אני?',hint:'הרכס של חיפה.',position:{x:49.11,y:15.84},hitEllipse:{x:49.11,y:15.84,rx:5.5,ry:3.8},location:'חיפה וצפון מישור החוף',type:'רכס הרים',height:'רכס חופי',feature:'חורש ירוק ומפגש ישיר עם הים.',importance:'רכס חופי ייחודי המפריד בין אזורים גאוגרפיים.',featureChoices:['חורש ירוק ומפגש ישיר עם הים','פסגה מושלגת','הר געש כבוי'],featureAnswer:'חורש ירוק ומפגש ישיר עם הים'},
{id:'bental',number:6,name:'הר בנטל',zone:'north',riddle:'אני משמש נקודת תצפית אסטרטגית וחשובה ברמת הגולן, ומפסגתי ניתן לראות ביום בהיר עמוק לתוך סוריה ועד לאזור דמשק. מי אני?',hint:'בצפון רמת הגולן.',position:{x:93.36,y:4.49},hitEllipse:{x:93.36,y:4.49,rx:3.0,ry:1.45},location:'צפון רמת הגולן',type:'הר געש כבוי',height:'פסגת תצפית',feature:'תצפית לסוריה ולדמשק.',importance:'נקודה אסטרטגית בצפון הגולן.',featureChoices:['תצפית לסוריה ולדמשק','נמצא במרכז ירושלים','חוף ים'],featureAnswer:'תצפית לסוריה ולדמשק'},
{id:'adar',number:7,name:'הר אדר',zone:'center',riddle:'אני שוכן באזור הרי ירושלים, והאתר שעליי מסמל את הקרבות הקשים ואת פריצת הדרך לעיר הבירה במהלך מלחמת השחרור. מי אני?',hint:'מערבית לירושלים.',position:{x:55.59,y:39.52},hitEllipse:{x:55.59,y:39.52,rx:3.0,ry:1.45},location:'הרי ירושלים',type:'הר ואתר הנצחה',height:'פסגה אזורית',feature:'קשור לקרבות הדרך לירושלים.',importance:'נקודת זיכרון מרכזית במלחמת העצמאות.',featureChoices:['קשור לקרבות הדרך לירושלים','הר געש פעיל','פסגה מושלגת'],featureAnswer:'קשור לקרבות הדרך לירושלים'},
{id:'scopus',number:8,name:'הר הצופים',zone:'center',riddle:'שמי מעיד שניתן "לצפות" ממני על ירושלים העתיקה ועל הר הבית, ובעבר הייתי מובלעת ישראלית מבודדת. מי אני?',hint:'ממזרח למרכז ירושלים.',position:{x:64.41,y:39.12},hitEllipse:{x:64.41,y:39.12,rx:3.0,ry:1.45},location:'ירושלים',type:'הר עירוני',height:'רכס ירושלים',feature:'תצפית לעיר העתיקה ולהר הבית.',importance:'מוקד לאומי ואקדמי בירושלים.',featureChoices:['תצפית לעיר העתיקה ולהר הבית','נמצא מול הים התיכון','מכתש מדברי'],featureAnswer:'תצפית לעיר העתיקה ולהר הבית'},
{id:'ramon',number:9,name:'הר רמון',zone:'south',riddle:'אני ההר הגבוה ביותר מבין כל הרי הנגב, ומראש הפסגה שלי ניתן להשקיף על המכתש הגדול והמרשים מכולם. מי אני?',hint:'בקרבת מכתש רמון.',position:{x:24.03,y:72.41},hitEllipse:{x:24.03,y:72.41,rx:3.2,ry:1.55},location:'הר הנגב',type:'פסגה',height:'ההר הגבוה בנגב',feature:'תצפית על מכתש רמון.',importance:'נקודת גובה מרכזית בהר הנגב.',featureChoices:['תצפית על מכתש רמון','חוף ים','שלג קבוע'],featureAnswer:'תצפית על מכתש רמון'},
{id:'shlomo',number:10,name:'הר שלמה',zone:'south',riddle:'אני הר כהה, סלעי וחד הממוקם בדרום רכס הרי אילת, ומנקודת התצפית שעליי אפשר לראות בבת אחת ארבע מדינות שונות. מי אני?',hint:'ליד אילת.',position:{x:41.17,y:97.42},hitEllipse:{x:41.17,y:97.42,rx:3.2,ry:1.55},location:'הרי אילת',type:'הר סלעי',height:'פסגה דרומית',feature:'סלעי יסוד ותצפית לארבע מדינות.',importance:'יוצא דופן גאולוגי בשדרת ההר.',featureChoices:['סלעי יסוד ותצפית לארבע מדינות','יער ים תיכוני','רכס חופי'],featureAnswer:'סלעי יסוד ותצפית לארבע מדינות'},
{id:'gerizim',number:11,name:'הר גריזים',zone:'center',riddle:'אני מוכר במסורת כ"הר הברכה" וממוקם באזור השומרון. עד היום אני משמש כמקום מושבה ומרכזה של העדה השומרונית. מי אני?',hint:'מעל שכם.',position:{x:61.77,y:29.87},hitEllipse:{x:61.77,y:29.87,rx:3.0,ry:1.45},location:'השומרון, מעל שכם',type:'הר קדוש',height:'פסגת שומרון',feature:'הר הברכה ומרכז העדה השומרונית.',importance:'אתר דתי והיסטורי מרכזי.',featureChoices:['הר הברכה ומרכז העדה השומרונית','אתר סקי','מכתש'],featureAnswer:'הר הברכה ומרכז העדה השומרונית'},
{id:'arbel',number:12,name:'הר ארבל',zone:'north',riddle:'אני מצוק סלעי, זקוף ומרשים במיוחד, המזדקר בעוצמה מעל אזור הגליל התחתון ומשקיף ישירות על מי הכנרת. מי אני?',hint:'מערבית לכנרת.',position:{x:76.25,y:13.19},hitEllipse:{x:76.25,y:13.19,rx:3.1,ry:1.5},location:'מעל הכנרת',type:'מצוק והר',height:'מצוק תלול',feature:'מצוק תלול המשקיף על הכנרת.',importance:'נקודת תצפית טבעית מרכזית.',featureChoices:['מצוק תלול המשקיף על הכנרת','דיונות חול','פסגת שלג'],featureAnswer:'מצוק תלול המשקיף על הכנרת'},
{id:'karkom',number:13,name:'הר כרכום',zone:'south',riddle:'אני סמוך לגבול מצרים, מלא בציורי סלע עתיקים, ויש המזהים אותי עם הר סיני המקראי. מי אני?',hint:'במערב הר הנגב.',position:{x:30.64,y:78.29},hitEllipse:{x:30.64,y:78.29,rx:5.0,ry:3.6},location:'מערב הר הנגב, סמוך למצרים',type:'אזור הררי ואתר ארכאולוגי',height:'רכס מדברי',feature:'ציורי סלע עתיקים וזיהוי אפשרי עם הר סיני.',importance:'אתר ארכאולוגי ונופי ייחודי.',featureChoices:['ציורי סלע עתיקים וזיהוי אפשרי עם הר סיני','יער גשם','נמל ימי'],featureAnswer:'ציורי סלע עתיקים וזיהוי אפשרי עם הר סיני'}
];
const REQUIRED_COUNT=3, STORAGE_KEY='amitMountainsStationV1';
const state={queue:[],current:null,completedIds:[],requiredCompleted:0,bonusCompleted:0,score:0,streak:0,attempts:0,stage:'intro',zoom:1,exploreZoom:1,mapFitWidth:0,exploreFitWidth:0,suppressMapClickUntil:0};
const $=id=>document.getElementById(id), els={scoreValue:$('scoreValue'),streakValue:$('streakValue'),completedValue:$('completedValue'),requiredValue:$('requiredValue'),progressBar:$('progressBar'),phaseChip:$('phaseChip'),challengeNumber:$('challengeNumber'),challengeType:$('challengeType'),riddleTitle:$('riddleTitle'),riddleText:$('riddleText'),feedback:$('feedback'),hintBtn:$('hintBtn'),mapInstructions:$('mapInstructions'),currentMountainName:$('currentMountainName'),featureStep:$('featureStep'),featureChoices:$('featureChoices'),introStage:$('introStage'),startStationBtn:$('startStationBtn'),nameStage:$('nameStage'),mountainOptions:$('mountainOptions'),mapStage:$('mapStage'),mapViewport:$('mapViewport'),mapCanvas:$('mapCanvas'),mountainsMap:$('mountainsMap'),mapMarkers:$('mapMarkers'),clickMarker:$('clickMarker'),passportStage:$('passportStage'),passportType:$('passportType'),passportName:$('passportName'),passportLocation:$('passportLocation'),passportHeight:$('passportHeight'),passportFeature:$('passportFeature'),passportImportance:$('passportImportance'),continueBtn:$('continueBtn'),decisionStage:$('decisionStage'),exploreBtn:$('exploreBtn'),bonusBtn:$('bonusBtn'),remainingBonusText:$('remainingBonusText'),exploreStage:$('exploreStage'),exploreMapViewport:$('exploreMapViewport'),exploreMapCanvas:$('exploreMapCanvas'),exploreMountainsMap:$('exploreMountainsMap'),exploreMarkers:$('exploreMarkers'),finishBtn:$('finishBtn'),completeStage:$('completeStage'),finalMountains:$('finalMountains'),finalBonus:$('finalBonus'),finalScore:$('finalScore'),collectionCount:$('collectionCount'),collectionGrid:$('collectionGrid'),fitMapBtn:$('fitMapBtn'),zoomInBtn:$('zoomInBtn'),zoomOutBtn:$('zoomOutBtn'),resetMapBtn:$('resetMapBtn'),exploreFitMapBtn:$('exploreFitMapBtn'),exploreZoomInBtn:$('exploreZoomInBtn'),exploreZoomOutBtn:$('exploreZoomOutBtn'),exploreResetMapBtn:$('exploreResetMapBtn'),instructionsBtn:$('instructionsBtn'),closeInstructionsBtn:$('closeInstructionsBtn'),instructionsModal:$('instructionsModal'),mountainInfoModal:$('mountainInfoModal'),closeMountainInfoBtn:$('closeMountainInfoBtn'),mountainInfoType:$('mountainInfoType'),mountainInfoName:$('mountainInfoName'),mountainInfoLocation:$('mountainInfoLocation'),mountainInfoHeight:$('mountainInfoHeight'),mountainInfoFeature:$('mountainInfoFeature'),mountainInfoImportance:$('mountainInfoImportance'),resetBtn:$('resetBtn'),amitLogo:$('amitLogo'),logoFallback:$('logoFallback')};
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const get=id=>MOUNTAIN_LIBRARY.find(x=>x.id===id), remaining=()=>MOUNTAIN_LIBRARY.filter(x=>!state.completedIds.includes(x.id));
function chooseRequired(){return shuffle(['north','center','south'].map(z=>shuffle(MOUNTAIN_LIBRARY.filter(x=>x.zone===z))[0].id))}
function hideStages(){['introStage','nameStage','mapStage','passportStage','decisionStage','exploreStage','completeStage'].forEach(id=>els[id].hidden=true)}
function resetSidebar(){els.mapInstructions.hidden=els.featureStep.hidden=els.hintBtn.hidden=true;els.feedback.hidden=true}
function updateHud(){els.scoreValue.textContent=state.score;els.streakValue.textContent=state.streak;els.completedValue.textContent=`${state.completedIds.length}/13`;els.requiredValue.textContent=`${Math.min(state.requiredCompleted,3)}/3`;els.progressBar.style.width=`${Math.min(state.requiredCompleted/3,1)*100}%`}
function feedback(t,c){els.feedback.hidden=false;els.feedback.className=`feedback ${c}`;els.feedback.textContent=t}
function initialize(){Object.assign(state,{queue:chooseRequired(),current:null,completedIds:[],requiredCompleted:0,bonusCompleted:0,score:0,streak:0,attempts:0,stage:'intro',zoom:1,exploreZoom:1});hideStages();els.introStage.hidden=false;resetSidebar();updateHud();renderCollection();localStorage.removeItem(STORAGE_KEY)}
function loadNext(){if(!state.queue.length)return showDecision();state.current=get(state.queue.shift());state.stage='name';state.attempts=0;hideStages();els.nameStage.hidden=false;resetSidebar();els.phaseChip.textContent='שלב א׳ – זיהוי ההר';els.challengeNumber.textContent=state.completedIds.length+1;els.challengeType.textContent=state.requiredCompleted<3?'מתוך 3 משימות החובה':'הר בונוס';els.riddleTitle.textContent='מי אני והיכן אני נמצא?';els.riddleText.textContent=state.current.riddle;renderOptions();updateHud()}
function renderOptions(){els.mountainOptions.innerHTML='';shuffle(remaining()).forEach(m=>{const b=document.createElement('button');b.className='settlement-option';b.textContent=m.name;b.onclick=()=>chooseName(m,b);els.mountainOptions.appendChild(b)})}
function chooseName(m,b){if(state.stage!=='name')return;state.attempts++;if(m.id===state.current.id){state.score+=state.attempts===1?100:50;state.streak++;feedback(`מדויק! זיהיתם את ${m.name}.`,'success');updateHud();setTimeout(showMap,550)}else{state.streak=0;b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),350);feedback('נסו שוב לפי הרמזים הגאוגרפיים והנופיים.','try-again');els.hintBtn.hidden=false;updateHud()}}
function showMap(){state.stage='map';hideStages();els.mapStage.hidden=false;resetSidebar();els.mapInstructions.hidden=false;els.currentMountainName.textContent=state.current.name;els.phaseChip.textContent='שלב ב׳ – מיקום במפה';renderTaskMarkers();requestAnimationFrame(()=>fitWholeMap('task'))}
function handleMapClick(e){if(state.stage!=='map'||Date.now()<state.suppressMapClickUntil)return;const r=els.mountainsMap.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100,a=state.current.hitEllipse;els.clickMarker.hidden=false;els.clickMarker.style.left=`${x}%`;els.clickMarker.style.top=`${y}%`;if(((x-a.x)/a.rx)**2+((y-a.y)/a.ry)**2<=1){state.score+=50;state.streak++;state.stage='feature';renderCurrentMarker();feedback('המיקום נכון. נוסף סמן חום.','success');showFeature();updateHud()}else{state.streak=0;feedback('המיקום אינו מדויק מספיק. הגדילו ונסו שוב.','try-again');els.hintBtn.hidden=false;updateHud()}}
function showFeature(){els.featureStep.hidden=false;els.featureChoices.innerHTML='';els.phaseChip.textContent='שלב ג׳ – מאפיין ייחודי';shuffle(state.current.featureChoices).forEach(c=>{const b=document.createElement('button');b.className='choice-button';b.textContent=c;b.onclick=()=>{if(c===state.current.featureAnswer){state.score+=50;state.completedIds.push(state.current.id);state.requiredCompleted<3?state.requiredCompleted++:state.bonusCompleted++;updateHud();renderCollection();showPassport()}else{b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),350);feedback('נסו שוב.','try-again')}};els.featureChoices.appendChild(b)})}
function marker(m,interactive=false){const el=document.createElement(interactive?'button':'div');if(interactive)el.type='button';el.className=`mountain-marker ${interactive?'explore-marker':''}`;el.dataset.mountainId=m.id;const p=m.displayPosition||m.position;el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;el.title=m.name;el.setAttribute('aria-label',`פתיחת תעודת הזהות של ${m.name}`);const s=document.createElement('span');s.textContent=m.number;el.appendChild(s);if(interactive){el.addEventListener('pointerdown',e=>e.stopPropagation());el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openInfo(m)})}return el}
function renderCurrentMarker(){const el=marker(state.current);el.id=`mountain-${state.current.id}`;els.mapMarkers.appendChild(el)}
function renderTaskMarkers(){els.mapMarkers.innerHTML='';state.completedIds.forEach(id=>els.mapMarkers.appendChild(marker(get(id))))}
function showPassport(){state.stage='passport';hideStages();els.passportStage.hidden=false;resetSidebar();Object.assign(els.passportType,{textContent:state.current.type});els.passportName.textContent=state.current.name;els.passportLocation.textContent=state.current.location;els.passportHeight.textContent=state.current.height;els.passportFeature.textContent=state.current.feature;els.passportImportance.textContent=state.current.importance;save(false)}
function showDecision(){state.stage='decision';hideStages();els.decisionStage.hidden=false;resetSidebar();els.remainingBonusText.textContent=`נותרו ${remaining().length} הרים זמינים לבונוס.`}
function showExplore(){state.stage='explore';hideStages();els.exploreStage.hidden=false;resetSidebar();els.exploreMarkers.innerHTML='';MOUNTAIN_LIBRARY.forEach(m=>els.exploreMarkers.appendChild(marker(m,true)));requestAnimationFrame(()=>fitWholeMap('explore'))}
function openInfo(m){els.mountainInfoType.textContent=m.type;els.mountainInfoName.textContent=m.name;els.mountainInfoLocation.textContent=m.location;els.mountainInfoHeight.textContent=m.height;els.mountainInfoFeature.textContent=m.feature;els.mountainInfoImportance.textContent=m.importance;els.mountainInfoModal.hidden=false;els.mountainInfoModal.setAttribute('aria-hidden','false')}
function finish(){hideStages();els.completeStage.hidden=false;els.finalMountains.textContent=state.completedIds.length;els.finalBonus.textContent=state.bonusCompleted;els.finalScore.textContent=state.score;save(true)}
function renderCollection(){els.collectionCount.textContent=state.completedIds.length;els.collectionGrid.innerHTML=state.completedIds.length?'':'<p class="empty-collection">הכרטיס הראשון יופיע לאחר השלמת הר.</p>';state.completedIds.forEach(id=>{const m=get(id),c=document.createElement('article');c.className='collection-card';c.innerHTML=`<strong>${m.name}</strong><span>${m.location}</span><span>${m.type}</span>`;els.collectionGrid.appendChild(c)})}
function getFitWidth(v,i){if(!i.naturalWidth)return Math.max(240,v.clientWidth*.36);return Math.max(220,Math.min(v.clientWidth-8,(v.clientHeight-8)*(i.naturalWidth/i.naturalHeight)))}
function center(v){v.scrollLeft=Math.max(0,(v.scrollWidth-v.clientWidth)/2);v.scrollTop=Math.max(0,(v.scrollHeight-v.clientHeight)/2)}
function fitWholeMap(k){const ex=k==='explore',v=ex?els.exploreMapViewport:els.mapViewport,c=ex?els.exploreMapCanvas:els.mapCanvas,i=ex?els.exploreMountainsMap:els.mountainsMap,w=getFitWidth(v,i);state[ex?'exploreFitWidth':'mapFitWidth']=w;state[ex?'exploreZoom':'zoom']=1;c.style.width=`${w}px`;requestAnimationFrame(()=>center(v))}
function zoom(k,z){const ex=k==='explore',v=ex?els.exploreMapViewport:els.mapViewport,c=ex?els.exploreMapCanvas:els.mapCanvas,i=ex?els.exploreMountainsMap:els.mountainsMap,key=ex?'exploreZoom':'zoom',base=state[ex?'exploreFitWidth':'mapFitWidth']||getFitWidth(v,i);state[key]=Math.max(1,Math.min(5,z));c.style.width=`${base*state[key]}px`;requestAnimationFrame(()=>center(v))}
function pan(v){let a=false,m=false,sx,sy,sl,st,pid;v.addEventListener('pointerdown',e=>{if(e.button!==0)return;a=true;m=false;pid=e.pointerId;sx=e.clientX;sy=e.clientY;sl=v.scrollLeft;st=v.scrollTop});v.addEventListener('pointermove',e=>{if(!a||e.pointerId!==pid)return;const dx=e.clientX-sx,dy=e.clientY-sy;if(!m&&Math.hypot(dx,dy)>5)m=true;if(m){e.preventDefault();v.scrollLeft=sl-dx;v.scrollTop=st-dy}});const end=e=>{if(a&&e.pointerId===pid){if(m)state.suppressMapClickUntil=Date.now()+250;a=false}};v.addEventListener('pointerup',end);v.addEventListener('pointercancel',end)}
function save(completed){localStorage.setItem(STORAGE_KEY,JSON.stringify({completed,completedIds:state.completedIds,score:state.score,bonusCompleted:state.bonusCompleted}))}
els.startStationBtn.onclick=loadNext;els.hintBtn.onclick=()=>feedback(`רמז: ${state.current.hint}`,'try-again');els.mountainsMap.onclick=handleMapClick;els.continueBtn.onclick=()=>state.requiredCompleted>=3?showDecision():loadNext();els.exploreBtn.onclick=showExplore;els.bonusBtn.onclick=()=>{const r=remaining();if(r.length){state.queue=[shuffle(r)[0].id];loadNext()}else showExplore()};els.finishBtn.onclick=finish;els.fitMapBtn.onclick=()=>fitWholeMap('task');els.zoomInBtn.onclick=()=>zoom('task',state.zoom+.35);els.zoomOutBtn.onclick=()=>zoom('task',state.zoom-.35);els.resetMapBtn.onclick=()=>center(els.mapViewport);els.exploreFitMapBtn.onclick=()=>fitWholeMap('explore');els.exploreZoomInBtn.onclick=()=>zoom('explore',state.exploreZoom+.35);els.exploreZoomOutBtn.onclick=()=>zoom('explore',state.exploreZoom-.35);els.exploreResetMapBtn.onclick=()=>center(els.exploreMapViewport);els.instructionsBtn.onclick=()=>els.instructionsModal.hidden=false;els.closeInstructionsBtn.onclick=()=>els.instructionsModal.hidden=true;els.closeMountainInfoBtn.onclick=()=>{els.mountainInfoModal.hidden=true;els.mountainInfoModal.setAttribute('aria-hidden','true')};els.exploreMarkers.addEventListener('pointerdown',event=>{if(event.target.closest('.mountain-marker'))event.stopPropagation()});els.exploreMarkers.addEventListener('click',event=>{const button=event.target.closest('.mountain-marker[data-mountain-id]');if(!button)return;event.preventDefault();event.stopPropagation();const mountain=get(button.dataset.mountainId);if(mountain)openInfo(mountain)});els.mountainInfoModal.addEventListener('click',event=>{if(event.target===els.mountainInfoModal){els.mountainInfoModal.hidden=true;els.mountainInfoModal.setAttribute('aria-hidden','true')}});els.resetBtn.onclick=()=>{if(confirm('לאפס את התחנה?'))initialize()};els.amitLogo.onerror=()=>{els.amitLogo.hidden=true;els.logoFallback.hidden=false};pan(els.mapViewport);pan(els.exploreMapViewport);initialize();
